---
kind: pipeline
type: docker
name: backend

steps:
  - name: build
    image: golang:1.20.2
    volumes:
      - name: deps
        path: /go
    commands:
      - make

  - name: test
    image: golang:1.20.2
    volumes:
      - name: deps
        path: /go
    commands:
      - make test

  - name: linter
    image: golang:1.20.2
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
      - ./bin/golangci-lint run --timeout 5m
      - rm -r ./bin/

volumes:
  - name: deps
    host:
      path: /var/lib/cache/godeps/

---
kind: pipeline
type: docker
name: frontend

steps:
  - name: build
    image: node:lts
    commands:
      - make front

---
kind: pipeline
type: docker
name: notify

steps:
  - name: telegram
    image: appleboy/drone-telegram
    settings:
      to: 790376882
      token:
        from_secret: telegram_token

depends_on:
  - backend
  - frontend
trigger:
  status:
    - success
    - failure
