builds:
- goarch: [amd64, arm, arm64, 386]
  goarm: [6, 7]
  goos: [linux,darwin,windows]
  env:
  - CGO_ENABLED=0
  main: ./main.go
  binary: vuemonit
  ldflags:
   - -s -w -X "main.Version={{ .Env.VERSION }}" -X "main.Build={{ .Env.BUILD }}"
archive:
  wrap_in_directory: true
  format: tar.gz
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
